version: '3'

services:
  api:
    build: backend
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '80:3000'
    depends_on:
      - api

volumes:
  node-modules: